import Dashboard from "@/components/dashboard";
import "./globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* <AuthProvider> */}
        <Dashboard>
          <div className="flex">
            <main>{children}</main>
          </div>
        </Dashboard>
        {/* </AuthProvider> */}
      </body>
    </html>
  );
}
